DLsystem/deep/forms.py
import numpy as np
from flask_wtf import FlaskForm, Form
from wtforms.validators import DataRequired, InputRequired, required
from wtforms import StringField, SubmitField, SelectField, FieldList
from flask_wtf.file import FileField
from flask_wtf.file import FileRequired


class EncoderResultForm(FlaskForm):
    choice_epochs = [(el, el) for el in range(100, 3100, 100)]
    epochs = SelectField('Epochs', choices=choice_epochs, validators=[InputRequired()], coerce=int)
    submit = SubmitField('Train again..')
    file = StringField(label='Filename', default='encoded_dataset')
    save_file = SubmitField(label='Save file')


class ResultForm(FlaskForm):
    choice_epochs = [(el, el) for el in range(100, 3100, 100)]
    epochs = SelectField('Epochs', choices=choice_epochs, validators=[InputRequired()], coerce=int)

    choice_alpha = [(el, "{0:.3f}".format(el)) for el in np.arange(0.000, 1.0, 0.003)]
    choice_alpha[0] = (0.001, '0.001')
    alpha = SelectField('Learning rate', choices=choice_alpha,
                        validators=[InputRequired()], coerce=float)
    submit = SubmitField('Train again..')


class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[DataRequired()])
    submit = SubmitField('Submit')


class LayerForm(FlaskForm):
    nodes_number = SelectField('Choose number of nodes',
                               choices=[(el, el) for el in range(0, 50)], validators=[InputRequired()], coerce=int)


class AutoEncoderForm(FlaskForm):
    target_col = SelectField('Target column(class identifier)', choices=[], validators=[InputRequired()], coerce=str)

    choice_epochs = [(el, el) for el in range(100, 3100, 100)]
    choice_test = [(el, el) for el in range(0, 101)]
    test_size = SelectField('Test set [%]', choices=choice_test, validators=[InputRequired()], coerce=int)
    epochs = SelectField('Epochs', choices=choice_epochs, validators=[InputRequired()], coerce=int)
    choice_factor = [(el, el) for el in range(2, 16, 2)]
    encode_factor = SelectField('Compression factor', choices=choice_factor, validators=[InputRequired()], coerce=int)

    submit = SubmitField('Submit')


class ParameterForm(FlaskForm):
    target_col = SelectField('Target column(class identifier)', choices=[], validators=[InputRequired()], coerce=str)

    choice_test = [(el, el) for el in range(0, 101)]
    test_size = SelectField('Test set [%]', choices=choice_test, validators=[InputRequired()], coerce=int)

    # net_config = StringField('Nodes in layers', validators=[InputRequired()])
    # n_layers = SelectField('Number of layers', choices=[(el, el) for el in range(0, 10)],
    #                        validators=[InputRequired()], coerce=int)
    #
    # layers = FieldList(FormField(LayerForm))
    # nodes_in_layer = []
    # for i in n_layers:
    #     nodes_in_layer[i] = SelectField('Nodes in layer {}'.format(i),
    #                                     choice=[(el, el) for el in range(0, 50)], validators=[InputRequired()])

    activation_func = SelectField('Activation function',
                                  choices=[('Sigmoid', 'Sigmoid'), ('Softmax', 'Softmax')], validators=[InputRequired()], coerce=str)

    choice_epochs = [(el, el) for el in range(100, 3100, 100)]
    epochs = SelectField('Epochs', choices=choice_epochs, validators=[InputRequired()], coerce=int)

    choice_alpha = [(el, "{0:.3f}".format(el)) for el in np.arange(0.000, 1.0, 0.003)]
    choice_alpha[0] = (0.001, '0.001')
    alpha = SelectField('Learning rate', choices=choice_alpha,
                        validators=[InputRequired()], coerce=float)

    submit = SubmitField('Submit')

    # def __init__(self, *args, **kwargs):
    #    print(args[0])
    #    print(kwargs)
    #    super(ParameterForm, self).__init__(*args, **kwargs)
    #    if not isinstance(args[0], list):
    #        args[0] = [args[0]]
    #    self.target_col.choices = args[0]


class SimpleUpload(FlaskForm):
    file = FileField('Choose the file', [required()])
    extension = SelectField('File type', choices=[('excel', 'excel'), ('csv', 'csv')],
                            validators=[InputRequired()], coerce=str)
    index_col = SelectField('Index column', choices=[('None', 'None'), ('0', 'First'), ('-1', 'Last')],
                            validators=[InputRequired()], coerce=str)
    header = SelectField('Header', choices=[('None', 'None'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')],
                         validators=[InputRequired()], coerce=str)
    submit = SubmitField('Submit')


class UploadForm(SimpleUpload):
    n_layers = SelectField('Number of layers', choices=[(el, el) for el in range(0, 10)],
                           validators=[InputRequired()], coerce=int)

DLsystem/deep/__init__.py
# -*- coding: utf-8 -*-
"""The deep learning module, including the MLP and autoencoder."""
from . import views

DLsystem/deep/views.py
import os
import pandas as pd
from dlsys.neuralnet import NeuralNet
from dlsys.autoencoder import AutoEncoder
from flask import Flask, render_template, session, redirect, \
    url_for, flash, request, Blueprint, g
from DLsystem.deep.forms import NameForm, ParameterForm, UploadForm, \
    ResultForm, SimpleUpload, AutoEncoderForm, EncoderResultForm
from werkzeug.utils import secure_filename
from wtforms.validators import InputRequired
from wtforms import SelectField
from DLsystem.utils import flash_errors


blueprint = Blueprint('deep', __name__, url_prefix='/', static_folder='../static')

basedir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))


def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        return False


def has_column_name(column_values):
    are_numbers = [True for val in column_values if is_number(val)]
    if True in are_numbers:
        return False
    return True


def load_dataset(destination, index_col, header, ext):
    """

    :param destination: path to folder where the file is located
    :param index_col: the integer: most likely 0 or -1
    :param header: the integer. Eg. 0 indicating that the first row is header
    :param ext: extension that is the format of the file .csv or .xlsx
    :return: loaded pandas dataframe
    """
    if ext == 'csv':
        data_set = pd.read_csv(destination, index_col=index_col, header=header)
    elif ext == 'excel':
        data_set = pd.read_excel(destination, index_col=index_col, header=header)

    return data_set


@blueprint.route('/mlp_net', methods=['GET', 'POST'])
def mlp_net():
    try:
        global data_set
        # check if the indexed column shall be None or integer value.
        if session['index_col'] != "None":
            index_col = int(session['index_col'])
        else:
            index_col = None
        if session['header'] != "None":
            header = int(session['header'])
        else:
            header = None
        data_set = load_dataset(destination=session['destination'],
                                index_col=index_col, header=header, ext=session['extension'])

        class NodesInLayers(ParameterForm):
            pass

        for i in range(0, session['n_layers']):
            if i == 0:
                default = data_set.shape[1] - 1
            elif i == session['n_layers'] - 1:
                default = 3
                #     default = len(data_set[target_col].unique())
            else:
                default = 16

            setattr(NodesInLayers, 'layer{}'.format(i + 1),
                    SelectField('Nodes in layer {}'.format(i + 1),
                                choices=[(el, el) for el in range(0, 50)], validators=[InputRequired()], coerce=int,
                                default=default)
                    )
        form = NodesInLayers()

        if has_column_name(data_set.columns.values):
            column_names = [(el, el) for el in data_set.columns]
        else:
            column_names = [(str(el), str(el)) for el in data_set.columns]

        form.target_col.choices = column_names
        global net
        if form.validate_on_submit():
            layers_nodes = [getattr(form, 'layer{}'.format(i + 1)).data for i in range(0, session['n_layers'])]
            if is_number(form.target_col.data):
                target_col = int(form.target_col.data)
            else:
                target_col = form.target_col.data
            net = NeuralNet(data_set=data_set, target_col=target_col)
            net.train_test_shuffle(form.test_size.data, seed=1234)
            net.configure_net(layers_nodes, activ_func=form.activation_func.data)
            # net_train = net.train(form.alpha.data, form.epochs.data)
            # net_test = net.test_model()
            return redirect(url_for('deep.result', alpha=form.alpha.data, epochs=form.epochs.data))
        return render_template('deep/mlp_net.html', dataset=data_set.to_html(), form=form, n_layers=session['n_layers'])
    except UnboundLocalError:
        return redirect(url_for('public.home'))


@blueprint.route('/result/alpha=<alpha>epochs=<epochs>', methods=['GET', 'POST'])
def result(alpha, epochs):
    form = ResultForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            epochs = form.epochs.data
            alpha = form.alpha.data

            net_train = net.train(alpha, epochs)
            net_test = net.test_model()
            flash("The model has been trained again.")
            render_template('deep/result.html', form=form, net_train=net_train, net_test=net_test)
        else:
            flash_errors(form)

    net_train = net.train(float(alpha), int(epochs))
    net_test = net.test_model()

    return render_template('deep/result.html', form=form, net_train=net_train, net_test=net_test)


@blueprint.route('/result_encoder?epochs=<epochs>?test_size=<test_size>?factor=<encode_factor>?target=<target_col>',
                 methods=['GET', 'POST'])
def result_encoder(epochs, test_size, encode_factor, target_col):
    encoder = AutoEncoder(data_set, int(test_size), int(encode_factor), target_col)
    encoder.compile()
    form = EncoderResultForm()

    encoder.fit(nb_epoch=int(epochs))
    loss_history = encoder.get_history_callback()
    summary = encoder.get_summary()
    df = encoder.get_encoded_df()

    if request.method == 'POST':
        if form.validate_on_submit():
            if form.save_file.data:
                target = os.path.join(basedir, 'dlsys/data/')
                df.to_csv(target+form.file.data+'.csv')
                flash("The file has been saved", 'success')

            if form.submit.data:
                epochs = form.epochs.data
                encoder.fit(nb_epoch=form.epochs.data)
                flash("The model has been fit again.")

            return redirect(url_for('deep.result_encoder', epochs=epochs,
                                    test_size=test_size, encode_factor=encode_factor,
                                    target_col=target_col))
        else:
            flash_errors(form)

    return render_template('deep/result_encoder.html', form=form, loss_history=loss_history,
                           summary=summary, df=df.to_html())


@blueprint.route('/autoencoder', methods=['GET', 'POST'])
def autoencoder():
    # check if the indexed column shall be None or integer value.
    global data_set
    if session['index_col'] != "None":
        index_col = int(session['index_col'])
    else:
        index_col = None
    if session['header'] != "None":
        header = int(session['header'])
    else:
        header = None
    data_set = load_dataset(destination=session['destination'],
                            index_col=index_col, header=header, ext=session['extension'])

    form = AutoEncoderForm()

    if has_column_name(data_set.columns.values):
        column_names = [(el, el) for el in data_set.columns]
    else:
        column_names = [(str(el), str(el)) for el in data_set.columns]

    form.target_col.choices = column_names

    if form.validate_on_submit():
        return redirect(url_for('deep.result_encoder', epochs=form.epochs.data, test_size=
                                form.test_size.data, encode_factor=form.encode_factor.data,
                                target_col=form.target_col.data))

    return render_template('deep/autoencoder.html', form=form, dataset=data_set.to_html())


@blueprint.route('/simple_upload', methods=['GET', 'POST'])
def simple_upload():
    form = SimpleUpload()
    target = os.path.join(basedir, 'dlsys/data')
    if not os.path.isdir(target):
        os.mkdir(target)

    if form.validate_on_submit():
        print(form.file.data.filename)
        filename = secure_filename(form.file.data.filename)
        destination = "/".join([target, filename])
        print(destination)
        form.file.data.save(destination)

        session['extension'] = form.extension.data
        session['destination'] = destination
        session['index_col'] = form.index_col.data
        session['header'] = form.header.data
        return redirect(url_for('deep.autoencoder'))
    return render_template('deep/simple_upload.html', form=form)


@blueprint.route('/upload', methods=['GET', 'POST'])
def upload():
    form = UploadForm()
    target = os.path.join(basedir, 'dlsys/data')

    if not os.path.isdir(target):
        os.mkdir(target)

    if form.validate_on_submit():
        print(form.file.data.filename)
        filename = secure_filename(form.file.data.filename)
        destination = "/".join([target, filename])
        print(destination)
        form.file.data.save(destination)

        session['extension'] = form.extension.data
        session['destination'] = destination
        session['index_col'] = form.index_col.data
        session['header'] = form.header.data
        session['n_layers'] = form.n_layers.data
        return redirect(url_for('deep.mlp_net'))
    return render_template('deep/upload.html', form=form)

# target_col <-- buttion choice
# test_size <-- percentage button
# net config <-- 4 pola
# activation function <-- button choice
# alpha <--- rozwijany
# epochs <-- rozwijany

DLsystem/templates/deep/autoencoder.html
{% extends "layout.html" %}


{% block scripts %}
    {{ super() }}
    <script src="https://code.jquery.com/jquery-2.1.4.js"></script>
    <script src="{{ url_for("static", filename="js/add_button.js") }}"></script>
{% endblock %}

{% block content %}

    <div class="jumbotron">

<div class="page-header">
<div class="row">
    <h1>The file has been loaded.</h1>
</div>
</div>
<p>


<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Unfold Dataset
</button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    {{ dataset | safe }}
  </div>
</div>

<div class="row">

</div>
    </div>
    <div class="jumbotron">
    <h1>Now let us configure the net</h1>
{#    <h2>You may choose the parameters</h2>#}
<form class="form form-horizontal" method="post" role="form">
  {{ form.hidden_tag() }}
  {{ wtf.form_errors(form, hiddens="only") }}

  {{ wtf.form_field(form.target_col) }}
  {{ wtf.form_field(form.test_size) }}
  {{ wtf.form_field(form.epochs) }}
  {{ wtf.form_field(form.encode_factor) }}
  {{ wtf.form_field(form.submit) }}
</form>


    </div>
    <div class="col-lg">
    <button class="btn btn-info" onclick="location.href='{{ url_for('deep.simple_upload') }}';">
                Back to upload
    </button>
    </div>

{% endblock %}

DLsystem/templates/deep/mlp_net.html
{% extends "layout.html" %}


{% block scripts %}
    {{ super() }}
    <script src="https://code.jquery.com/jquery-2.1.4.js"></script>
    <script src="{{ url_for("static", filename="js/add_button.js") }}"></script>
{% endblock %}

{% block content %}

    <div class="jumbotron">

<div class="page-header">
<div class="row">
    <h1>The file has been loaded.</h1>
</div>
</div>
<p>


<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Unfold Dataset
</button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    {{ dataset | safe }}
  </div>
</div>

<div class="row">

</div>
    </div>
    <div class="jumbotron">
    <h1>Now let us configure the net</h1>
{#    <h2>You may choose the parameters</h2>#}
<form class="form form-horizontal" method="post" role="form">
  {{ form.hidden_tag() }}
  {{ wtf.form_errors(form, hiddens="only") }}

  {{ wtf.form_field(form.target_col) }}
  {{ wtf.form_field(form.activation_func) }}
  {{ wtf.form_field(form.test_size) }}
  {{ wtf.form_field(form.epochs) }}
  {{ wtf.form_field(form.alpha) }}
    {%  for i in range(n_layers) %}
        {{ wtf.form_field(form['layer{}'.format(i + 1)]) }}
    {% endfor %}
  {{ wtf.form_field(form.submit) }}
</form>


    </div>
            <div class="col-lg">
    <button class="btn btn-info" onclick="location.href='{{ url_for('deep.upload') }}';">
                Back to upload
    </button>
    </div>

{% endblock %}

DLsystem/templates/deep/result.html
{% extends "layout.html" %}

{% block content %}
            <div class="col-lg">
            <button class="btn btn-info" onclick="location.href='{{ url_for('deep.mlp_net') }}';">
                Reinitialize Net
            </button>
                 </div>
<div class="page-header" align="center">

            <h1 align="inline">Results</h1>

</div>
    <div class="jumbotron">
        <div class="container">
        {{ net_train | safe  }}
       </div>
        <div class="container">
        {{ net_test | safe  }}
        </div>
    </div>
    <div class="container main">
        <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                  <th scope="col"></th>
                  <th scope="col">Alpha</th>
                  <th scope="col">Epochs</th>
                </tr>
          </thead>
              <tbody>
              <form class="form form-vertical" method="post" role="form">
                        {{ form.hidden_tag() }}
                        {{ wtf.form_errors(form, hiddens="only") }}
                  <tr class="bg-warning">
                      <td>{{ form.submit(class="btn btn-default") }}</td>
                      <td>{{ form.alpha(class="form-control") }}</td>
                      <td>{{ form.epochs(class="form-control") }}</td>
                  </tr>
              </form>
              </tbody>
         </table>
        </div>
    </div>
{% endblock %}

DLsystem/templates/deep/result_encoder.html
{% extends "layout.html" %}

{% block content %}
            <div class="col-lg">
            <button class="btn btn-info" onclick="location.href='{{ url_for('deep.autoencoder') }}';">
                Reinitialize Autoencoder
            </button>
                 </div>
<div class="page-header" align="center">

            <h1 align="inline">Results</h1>

</div>
<div class="row">
    <div class="col-lg">
        <div class="jumbotron">

                {{ loss_history | safe }}
        </div>
    </div>
    <div class="col-lg">
        <div class="row">
            <div class="jumbotron">

                    <h1 align="center">Summary</h1>
                    {% for el in summary %}
                    {{ el | safe }}
                    {%  endfor %}

            </div>
        </div>
        <div class="row">
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                 Encoded Dataset
            </button>
            </p>
            <div class="collapse" id="collapseExample">
                <div class="card card-body">
                    {{ df | safe }}
                </div>
            </div>
        </div>

    </div>
</div>


<div class="container main">
<form class="form form-vertical" method="post" role="form">
<div class="row">
<div class="container main">
    <table class="table table-bordered">
        <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Epochs</th>
            </tr>
      </thead>
          <tbody>

                    {{ form.hidden_tag() }}
                    {{ wtf.form_errors(form, hiddens="only") }}
              <tr class="bg-warning">
                  <td>{{ form.submit(class="btn btn-default") }}</td>
                  <td>{{ form.epochs(class="form-control") }}</td>
              </tr>

          </tbody>
     </table>
</div>
</div>

    <div class="row">
        <div class="container main">
            <div class="col">
            <h3>Save encoded dataset</h3>
            {{ form.file(class="btn btn-default") }}
            {{ form.save_file(class="btn btn-warning") }}

            </div>

        </div>
    </div>
            </form>
            <div class="row">
                <div class="container main">
                        <button class="btn btn-info" onclick="location.href='{{ url_for('deep.upload') }}';">
                            connect to MLP
                        </button>
                </div>
            </div>



</div>

{% endblock %}

DLsystem/templates/deep/simple_upload.html
{% extends "layout.html" %}


{% block content %}

<div class="page-header" align="center">
    <h1>Hello {{ current_user.username }}!</h1>
</div>


    <div class="jumbotron vertical-center">
    <div class="container">
<form class="form form-vertical" method="post" enctype="multipart/form-data" role="form">
  {{ form.hidden_tag() }}
  {{ wtf.form_errors(form, hiddens="only") }}

    <h4>Please choose proper file containing dataset.</h4>

  {{ wtf.form_field(form.file) }}
  {{ wtf.form_field(form.extension) }}
  {{ wtf.form_field(form.index_col) }}
  {{ wtf.form_field(form.header) }}

  {{ wtf.form_field(form.submit) }}

</form>
        </div>
    </div>
{% endblock %}

DLsystem/templates/deep/upload.html
{% extends "layout.html" %}


{% block content %}

<div class="page-header" align="center">
    <h1>Hello {{ current_user.username }}!</h1>
{#    <h2>File Upload.</h2>#}
</div>


    <div class="jumbotron vertical-center">
    <div class="container">
<form class="form form-vertical" method="post" enctype="multipart/form-data" role="form">
  {{ form.hidden_tag() }}
  {{ wtf.form_errors(form, hiddens="only") }}

    <h4>Please choose proper file containing dataset.</h4>

  {{ wtf.form_field(form.file) }}
  {{ wtf.form_field(form.extension) }}
  {{ wtf.form_field(form.index_col) }}
  {{ wtf.form_field(form.header) }}

    <h2>Initial configuration of neural network.</h2>
  {{ wtf.form_field(form.n_layers) }}
  {{ wtf.form_field(form.submit) }}

</form>
        </div>
    </div>
{% endblock %}